exam/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^shopping/', include('shopping.urls', namespace='shopping')),
    url(r'^$', lambda request: redirect('/shopping/')),
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^category/new/$', views.category_new, name='category_new'),
    url(r'^category/(?P<pk>\d+)/edit/$', views.category_edit, name='category_edit'),
    url(r'^category/(?P<pk>\d+)/$', views.category_detail, name='category_detail'),
    url(r'^category/(?P<pk>\d+)/delete/$', views.category_delete, name='category_delete'),
    url(r'^category/(?P<category_pk>\d+)/shop/new/$', views.shop_new, name='shop_new'),
    url(r'^category/(?P<category_pk>\d+)/shop/(?P<pk>\d+)/edit/$', views.shop_edit, name='shop_edit'),
    url(r'^category/(?P<category_pk>\d+)/shop/(?P<pk>\d+)/$', views.shop_detail, name='shop_detail'),
    url(r'^category/(?P<category_pk>\d+)/shop/(?P<pk>\d+)/delete/$', views.shop_delete, name='shop_delete'),
    url(r'^category/(?P<category_pk>\d+)/shop/(?P<shop_pk>\d+)/review/new/$', views.review_new, name='review_new'),
    url(r'^category/(?P<category_pk>\d+)/shop/(?P<shop_pk>\d+)/review/(?P<pk>\d+)/edit/$', views.review_edit, name='review_edit'),
    url(r'^category/(?P<category_pk>\d+)/shop/(?P<shop_pk>\d+)/review/(?P<pk>\d+)/delete/$', views.review_delete, name='review_delete'),

]

shopping/models.py
from django.conf import settings
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Shop(models.Model):
    category = models.ForeignKey(Category)
    name = models.CharField(max_length=40)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    intro = models.TextField()
    image1 = models.ImageField()
    image2 = models.ImageField()
    image3 = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Review(models.Model):
    shop = models.ForeignKey(Shop)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    message = models.TextField()
    image = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

shopping/forms.py
from django import forms
from .models import Category, Shop, Review

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', ]


class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ['name', 'phone', 'address', 'intro', 'image1', 'image2', 'image3',]


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['message', 'image',]

shopping/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .models import Category, Shop, Review
from .forms import CategoryForm, ShopForm, ReviewForm


def index(request):
    category_list = Category.objects.all()
    review_list = Review.objects.all().order_by('-created_at')[:9]
    return render(request, 'shopping/index.html', {
        'category_list' : category_list,
        'review_list' : review_list,
        })

@login_required
def category_new(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save()
            messages.success(request, '새로운 카테고리가 등록되었습니다.')
            return redirect('shopping:category_detail', category.pk)
    else:
        form = CategoryForm()
    return render(request, 'shopping/category_form.html', {
        'form' : form
        })


@login_required
def category_edit(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            category = form.save()
            messages.success(request, '카테고리가 수정되었습니다.')
            return redirect('shopping:category_detail', category.pk)
    else:
        form = CategoryForm()
    return render(request, 'shopping/category_form.html', {
        'form' : form
        })


def category_detail(request, pk):
    category = get_object_or_404(Category, pk=pk)
    return render(request, 'shopping/category_detail.html', {
        'category' : category
        })


@login_required
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.delete()
    messages.error(request, "카테고리가 삭제되었습니다.")
    return redirect('shopping:index')



@login_required
def shop_new(request, category_pk):
    category = get_object_or_404(Category, pk=category_pk)
    if request.method == "POST":
        form = ShopForm(request.POST, request.FILES)
        if form.is_valid():
            shop = form.save(commit=False)
            shop.category = category
            shop.save()
            messages.success(request, '새로운 가게가 등록되었습니다.')
            return redirect('shopping:shop_detail', category.pk, shop.pk)
    else:
        form = ShopForm()
    return render(request, 'shopping/shop_form.html', {
        'form' : form,
        })


@login_required
def shop_edit(request, category_pk, pk):
    category = get_object_or_404(Category, pk=category_pk)
    shop = get_object_or_404(Shop, pk=pk)
    if request.method == "POST":
        form = ShopForm(request.POST, request.FILES, instance=shop)
        if form.is_valid():
            shop = form.save(commit=False)
            shop.category = category
            shop.save()
            messages.success(request, '가게가 수정되었습니다.')
            return redirect('shopping:shop_detail', category.pk, shop.pk)
    else:
        form = ShopForm()
    return render(request, 'shopping/shop_form.html', {
        'form' : form,
        })


def shop_detail(request, category_pk, pk):
    category = get_object_or_404(Category, pk=category_pk)
    shop = get_object_or_404(Shop, pk=pk)
    return render(request, 'shopping/shop_detail.html', {
        'category' : category,
        'shop' : shop,
        })


@login_required
def shop_delete(request, category_pk, pk):
    shop = get_object_or_404(Shop, pk=pk)
    shop.delete()
    messages.error(request, "가게가 삭제되었습니다.")
    return redirect('shopping:category_detail', category_pk)


@login_required
def review_new(request, category_pk, shop_pk):
    category = get_object_or_404(Category, pk=category_pk)
    shop = get_object_or_404(Shop, pk=shop_pk)
    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.shop = shop
            review.user = request.user
            review.save()
            messages.success(request, '새로운 리뷰가 등록되었습니다.')
            return redirect('shopping:shop_detail', category.pk, shop.pk)
    else:
        form = ReviewForm()
    return render(request, 'shopping/review_form.html', {
        'form' : form,
        })


@login_required
def review_edit(request, category_pk, shop_pk, pk):
    category = get_object_or_404(Category, pk=category_pk)
    shop = get_object_or_404(Shop, pk=shop_pk)
    review = get_object_or_404(Review, pk=pk)
    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES, instance=review)
        if form.is_valid():
            review = form.save(commit=False)
            review.shop = shop
            review.user = request.user
            review.save()
            messages.success(request, '리뷰가 수정되었습니다.')
            return redirect('shopping:shop_detail', category.pk, shop.pk)
    else:
        form = ReviewForm(instance=review)
    return render(request, 'shopping/review_form.html', {
        'form' : form
        })


@login_required
def review_delete(request, category_pk, shop_pk, pk):
    review = get_object_or_404(Review, pk=pk)
    review.delete()
    messages.error(request, "리뷰가 삭제되었습니다.")
    return redirect('shopping:shop_detail', category_pk, shop_pk)

shopping/templates/shopping/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf8"/>
<title>Beomjun's store center</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
<style>
body {
    padding-top: 60px;
    padding-bottom: 30px;
}
</style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href='{% url 'shopping:index' %}'>Beomjun's Store center</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'shopping:index' %}">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">로그아웃</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}">로그인</a></li>
                    <li><a href="{% url 'signup' %}">회원가입</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

shopping/templates/shopping/category_detail.html
{% extends 'shopping/base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h1>{{category.name}}
        <li class="btn btn-default"><a href="{% url 'shopping:shop_new' category.pk %}">새로운 가게 만들기</a></li>
        <li class="btn btn-default"><a href="{% url 'shopping:category_edit' category.pk %}">카테고리 수정하기</a></li>
        <li class="btn btn-default"><a href="{% url 'shopping:category_delete' category.pk %}">카테고리 삭제하기</a></li>
    </h1>
        <div class="col-sm-12">
            {% for shop in category.shop_set.all %}
            <div class="col-sm-4 caption">
                <a href="{% url 'shopping:shop_detail' category.pk shop.pk %}">
                {{shop.name}}
                <img src='{{shop.image1.url}}' style="max-width: 100%;"/>
                </a>
                <li class="btn btn-default"><a href="{% url 'shopping:shop_edit' category.pk shop.pk %}">가게 수정하기</a></li>
                <li class="btn btn-default"><a href="{% url 'shopping:shop_delete' category.pk shop.pk %}">가게 삭제하기</a></li>
            </div>
            {% endfor %}
        </div>
        <hr/>
{% endblock %}

shopping/templates/shopping/category_form.html
{% extends 'shopping/base.html' %}
{% load bootstrap3 %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {% bootstrap_form form %}
    </table>
    <input type="submit">
</form>
{% endblock %}

shopping/templates/shopping/index.html
{% extends 'shopping/base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <li class="btn btn-default"><a href="{% url 'shopping:category_new' %}">새로운 카테고리 만들기</a></li>
        {% for category in category_list %}
        <div class="col-sm-12">
            <a href="{% url 'shopping:category_detail' category.pk %}">
                <h1>{{category.name}}
                    <li class="btn btn-default">
                        <a href="{% url 'shopping:shop_new' category.pk %}">새로운 가게 만들기</a>
                    </li>
                    <li class="btn btn-default">
                        <a href="{% url 'shopping:category_edit' category.pk %}">카테고리 수정하기</a>
                    </li>
                    <li class="btn btn-default">
                        <a href="{% url 'shopping:category_delete' category.pk %}">카테고리 삭제하기</a>
                    </li>
                </h1>
            </a>
            <div class="col-sm-12">
                {% for shop in category.shop_set.all %}
                <div class="col-sm-4 caption">
                    <a href="{% url 'shopping:shop_detail' category.pk shop.pk %}">
                    <h3>{{shop.name}}</h3>
                    <img src='{{shop.image1.url}}' style="max-width: 100%;"/>
                    </a>
                </div>
                {% endfor %}
            </div>
            <hr/>
        </div>
        {% endfor %}
        <h2>최근 리뷰 목록</h2>
        {% for review in review_list %}
            <h5>
            {{review.message}} by {{review.user}} |
            {{review.created_at}}
            </h5>
        {% endfor %}

    </div>
{% endblock %}

shopping/templates/shopping/review_form.html
{% extends 'shopping/base.html' %}
{% load bootstrap3 %}

{% block content %}
<form action="" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <table>
        {% bootstrap_form form %}
    </table>
    {% buttons %}
    <button type="submit" class="btn btn-primary">{% bootstrap_icon "ok-sign" %} 리뷰 남기기</button>
    {% endbuttons %}
</form>
{% endblock %}

shopping/templates/shopping/shop_detail.html
{% extends 'shopping/base.html' %}
{% load bootstrap3 %}

{% block content %}
<h1>{{shop.name}}</h1>
<h3>전화번호 : {{shop.phone}} 주소 : {{shop.address}}</h3>
<hr/>
<h6>{{shop.intro}}</h6>
<div class="col-sm-12">
    <div class="col-sm-4">
    <img src="{{shop.image1.url}}" style="max-width: 100%;"/>
    </div>
    <div class="col-sm-4">
    <img src="{{shop.image2.url}}" style="max-width: 100%;"/>
    </div>
    <div class="col-sm-4">
    <img src="{{shop.image3.url}}" style="max-width: 100%;"/>
    </div>
</div>

<hr/>
<li class="btn btn-default"><a href="{% url 'shopping:review_new' category.pk shop.pk %}">댓글 쓰기<a></li>
<ul>
{% for review in shop.review_set.all %}
    <li>
        <img src="{{review.image.url}}"/>
        {{review.message}}
        by {{review.user}}
        {{review.created_at}}
        <a href="{% url 'shopping:review_edit' category.pk shop.pk review.pk %}">수정</a>
        <a href="{% url 'shopping:review_delete' category.pk shop.pk review.pk %}">삭제</a>
    </li>
{% endfor %}
</ul>
{% endblock %}

shopping/templates/shopping/shop_form.html
{% extends 'shopping/base.html' %}
{% load bootstrap3 %}

{% block content %}
<form action="" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <table>
        {% bootstrap_form form %}
    </table>
    <input type="submit">
</form>
{% endblock %}